name: Build and Push to Docker Hub

on:
  workflow_dispatch:
  push:
    branches:
      - main # Or your default branch

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

    - name: Build Docker image
      run: |
        docker build . \
          --build-arg YOUR_DISCORD_BOT_TOKEN=${{ secrets.YOUR_DISCORD_BOT_TOKEN }} \
          --build-arg YOUR_DISCORD_CLIENT_ID=${{ secrets.YOUR_DISCORD_CLIENT_ID }} \
          --build-arg YOUR_OPENAI_API_KEY=${{ secrets.YOUR_OPENAI_API_KEY }} \
          --build-arg YOUR_ALLOWED_SERVER_IDS=${{ secrets.YOUR_ALLOWED_SERVER_IDS }} \
          -t ${{ secrets.DOCKERHUB_USERNAME }}/your-image-name:latest

    - name: Push Docker image to Docker Hub
      run: |
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/your-image-name:latest