name: Build and Push to Docker Hub

on:
  workflow_dispatch:
  push:
    branches:
      - main # Or your default branch

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Boot builder instance
      run: docker buildx create --use

    - name: Build and Push Docker image
      run: |
        docker buildx build \
          --platform linux/amd64,linux/arm64 \
          --build-arg YOUR_DISCORD_BOT_TOKEN=${{ secrets.YOUR_DISCORD_BOT_TOKEN }} \
          --build-arg YOUR_DISCORD_CLIENT_ID=${{ secrets.YOUR_DISCORD_CLIENT_ID }} \
          --build-arg YOUR_OPENAI_API_KEY=${{ secrets.YOUR_OPENAI_API_KEY }} \
          --build-arg YOUR_ALLOWED_SERVER_IDS=${{ secrets.YOUR_ALLOWED_SERVER_IDS }} \
          -t ${{ secrets.DOCKERHUB_USERNAME }}/gpt-discord-bot:latest \
          --push .